strictness: veryhigh
doc-warnings: true

autodetect: false # There seem to be some issues with autodetect

ignore-paths:
  - docs
  - tests
  - _tasks.py
  - examples
  - example_data

pycodestyle:
  options:
    max-line-length: 120
  disable:
    - E127
    - W391
    - E203 # ignoring white space before colon :

mccabe:
  disable:
    # Disable complexity checks for now, as there seems to be no way to just disable the complexity check for a single
    # function in the new prospector versions
    - MC0001 # too complex

pydocstyle:
  options:
    convention: numpy
  disable:
    - D404
    - D100  # Missing docstring in public module, handled by pylint
    - D101  # Missing docstring in public class, handled by pylint
    - D102  # Missing docstring in public method, handled by pylint
    - D103  # Missing docstring in public function, handled by pylint
    - D104  # Missing docstring in public package, handled by pylint
    - D107  # Missing docstrings in __init__, we don't have them by convention
    - D203  # Blank line required before class docstring
    - D213  # Docstring Summary should start in second line


pylint:
  options:
    max-line-length: 120
    variable-rgx: "[a-z_][a-z0-9_]{0,50}$"  # Allow for single letter variable names
    argument-rgx: "[a-z_][a-z0-9_]{0,50}$"  # Allow for single letter argument names
    attr-rgx: "[a-z_][a-z0-9_]*$"  # Allow for single letter attribute names
    class-rgx: "[A-Z_][a-zA-Z0-9]*_?$" # Allow for single letter class names
  disable:
    - too-many-ancestors
    - too-few-public-methods
    - too-many-arguments
    - too-many-instance-attributes
    - abstract-method
    - invalid-unary-operand-type
    - too-many-locals # ignore the use of more than 15 local variables
    - invalid-unary-operand-type
    - protected-access
    - too-many-lines
    - bad-whitespace
    - cyclic-import # ignored because of false positive due to Type hints
    - import-error # We check if our dependencies are installed in the tests, no need for the linter
    - django-not-available # Don't use it... don't know why it is checked in the first place
    - consider-using-f-string # We use, but don't enforce f-strings
