import re
import shutil
import subprocess
import sys
from pathlib import Path

import toml

HERE = Path(__file__).parent


def task_docs(clean=False, builder="html") -> None:
    """Build the html docs using Sphinx."""
    # Delete Autogenerated files from previous run
    if clean:
        shutil.rmtree(str(HERE / "docs/modules/generated"), ignore_errors=True)
        shutil.rmtree(str(HERE / "docs/_build"), ignore_errors=True)
        shutil.rmtree(str(HERE / "docs/auto_examples"), ignore_errors=True)

    subprocess.run(f"sphinx-build -b {builder} -j auto -d docs/_build docs docs/_build/html", shell=True, check=True)


def update_version_strings(file_path, new_version) -> None:
    # taken from:
    # https://stackoverflow.com/questions/57108712/replace-updated-version-strings-in-files-via-python
    version_regex = re.compile(r"(^_*?version_*?\s*=\s*\")(\d+\.\d+\.\d+-?\S*)\"", re.M)
    with open(file_path, "r+") as f:
        content = f.read()
        f.seek(0)
        f.write(
            re.sub(
                version_regex,
                lambda match: f'{match.group(1)}{new_version}"',
                content,
            )
        )
        f.truncate()


def update_version(version) -> None:
    subprocess.run(["uv", "version", version, "--frozen"], shell=False, check=True)
    new_version = (
        subprocess.run(["uv", "version", "--short"], shell=False, check=True, capture_output=True)
        .stdout.decode()
        .strip()
    )
    update_version_strings(HERE / "gaitmap/__init__.py", new_version)
    # Update the gaitmap_mad version as well
    subprocess.run(
        ["uv", "version", new_version, "--project", str(HERE / "gaitmap_mad"), "--frozen"],
        shell=False,
        check=True,
    )
    update_version_strings(HERE / "gaitmap_mad/gaitmap_mad/__init__.py", new_version)


def task_update_version() -> None:
    update_version(sys.argv[1])


def task_bump_all_dev() -> None:
    """Bump all dev dependencies."""
    pyproject = toml.load(HERE.joinpath("pyproject.toml"))
    dev_dependencies = pyproject["dependency-groups"]["dev"]
    new_dev_deps = []

    for dep in dev_dependencies:
        dep_name_match = re.match(r"[A-Za-z0-9_.-]+", dep)
        if dep_name_match is None:
            continue
        dep_name = dep_name_match.group(0)
        if dep_name == "gaitmap-mad":
            continue
        new_dev_deps.append(f"{dep_name}@latest")

    subprocess.run(["uv", "add", "--group", "dev", *new_dev_deps], shell=False, check=True)
